apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbv3-client
  namespace: lbv3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lbv3-client
  template:
    metadata:
      labels:
        app: lbv3-client 
    spec:
      containers:
        - name: lbv3-client
          image: abdoabuharrus/lbv3.0:sed1.0
          ports:
            - containerPort: 84
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          env:
            - name: VITE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lbv3-flask-secret
                  key: VITE_SUPABASE_URL
            - name: VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY
              valueFrom:
                secretKeyRef:
                  name: lbv3-flask-secret
                  key: VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY
            - name: VITE_BACKEND_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: lbv3-flask-secret
                  key: VITE_BACKEND_BASE_URL
      volumes:
        - name: config-volume
          configMap:
            name: nginx-client-config
